name: 'Download Everest CI artifact'
inputs:
  name:
    description: 'Name of the artifact, e.g. FStar'
    required: true
  set_home:
    description: 'Set the _HOME variables specified by the artifact. Default: true'
    default: true

runs:
  using: "composite"
  steps:
    - name: Get artifact
      uses: actions/download-artifact@master
      with:
        name: ${{ inputs.name }}

    - name: Untar
      shell: bash
      run: tar xzf '${{ inputs.name }}.tar.gz'

    - name: Remove tarball
      shell: bash
      run: rm '${{ inputs.name }}.tar.gz'

    - name: Process home tags
      if: ${{ inputs.set_home }}
      shell: bash
      run: |
        find . -name .hometag | 
        while read f; do
          H=$(cat $f)
          echo "${H}_HOME=$(realpath $(dirname $f))" >> $GITHUB_ENV
          rm -f $f
        done 
